/**
 * Writes the published files of @veljaos/tokens from src/tokens.ts: tokens.css (the --liro-*
 * variables and the base typography), fonts.css (the font faces), theme.css (the Tailwind v4
 * theme) and tokens.json.
 */
import {
  BRAND_STACK,
  BREAKPOINTS,
  COMMON,
  DURATION,
  EASING,
  FAMILIES,
  FONT_CJK_ORDER,
  FONT_SIZE,
  FONT_WEIGHT,
  HEADINGS,
  kebab,
  LAYERS,
  LEADING,
  MONO_STACK,
  RELAXED_SCRIPT_LANGUAGES,
  sansStack,
  TRACKING,
  MEANINGS,
  meaningEntries,
  RADIUS,
  RAMPS,
  resolvedTokens,
  SHADOWS,
  SIZES,
  SPACE,
  TONES,
  valueVariable,
  type Theme,
} from './tokens.ts'

const HEADER = '/* Generated by @veljaos/tokens from src/tokens.ts. Do not edit. */'

/** A meaning's value in CSS: a value reference becomes var(--liro-…), a literal stays. */
function cssValue(reference: string): string {
  const variable = valueVariable(reference)
  return variable === null ? reference : `var(${variable})`
}

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((line) => (line === '' ? '' : `  ${line}`)).join('\n')}\n}`
}

/**
 * shadcn/ui's variables mapped onto Liro meanings, so copied primitives look Liro without edits.
 * Liro components use the Liro names.
 */
export const SHADCN: Record<string, string> = {
  radius: '--liro-radius-md',
  background: '--liro-surface-page',
  foreground: '--liro-text-primary',
  card: '--liro-surface-raised',
  'card-foreground': '--liro-text-primary',
  popover: '--liro-surface-overlay',
  'popover-foreground': '--liro-text-primary',
  primary: '--liro-brand-solid',
  'primary-foreground': '--liro-brand-on-solid',
  secondary: '--liro-surface-sunken',
  'secondary-foreground': '--liro-text-primary',
  muted: '--liro-surface-sunken',
  'muted-foreground': '--liro-text-secondary',
  accent: '--liro-surface-hover',
  'accent-foreground': '--liro-text-primary',
  destructive: '--liro-status-danger-solid',
  'destructive-foreground': '--liro-text-on-accent',
  border: '--liro-border-default',
  input: '--liro-border-strong',
  ring: '--liro-border-focus',
}

export function tokensCss(): string {
  const values: string[] = ['/* A.1 Colour ramps (0 = lightest, 9 = darkest) and common colours */']
  for (const [ramp, steps] of Object.entries(RAMPS)) {
    steps.forEach((value, step) => values.push(`--liro-${ramp}-${String(step)}: ${value};`))
  }
  for (const [name, value] of Object.entries(COMMON)) {
    values.push(`--liro-${kebab(name)}: ${value};`)
  }
  values.push('', '/* A.3 Spacing and radius */')
  for (const [name, value] of Object.entries(SPACE)) values.push(`--liro-space-${name}: ${value};`)
  for (const [name, value] of Object.entries(RADIUS))
    values.push(`--liro-radius-${name}: ${value};`)
  values.push(
    '',
    '/* A.4 Motion, breakpoints (for reference: media queries cannot read variables), sizes, layers */',
  )
  for (const [name, value] of Object.entries(DURATION))
    values.push(`--liro-duration-${name}: ${value};`)
  for (const [name, value] of Object.entries(EASING)) values.push(`--liro-ease-${name}: ${value};`)
  for (const [name, value] of Object.entries(BREAKPOINTS))
    values.push(`--liro-breakpoint-${name}: ${value};`)
  for (const [name, value] of Object.entries(SIZES))
    values.push(`--liro-size-${kebab(name)}: ${value};`)
  for (const [name, value] of Object.entries(LAYERS)) values.push(`--liro-layer-${name}: ${value};`)
  values.push('', '/* A.5 Typography */')
  values.push(`--liro-font-sans: ${sansStack(FONT_CJK_ORDER.default)};`)
  values.push(`--liro-font-brand: ${BRAND_STACK};`)
  values.push(`--liro-font-mono: ${MONO_STACK};`)
  for (const [name, value] of Object.entries(FONT_SIZE))
    values.push(`--liro-font-size-${name}: ${value};`)
  for (const [name, value] of Object.entries(FONT_WEIGHT))
    values.push(`--liro-font-weight-${name}: ${value};`)
  for (const [name, value] of Object.entries(LEADING))
    values.push(`--liro-leading-${name}: ${value};`)
  for (const [name, value] of Object.entries(TRACKING))
    values.push(`--liro-tracking-${name}: ${value};`)
  for (const [level, [size, lineHeight]] of Object.entries(HEADINGS)) {
    values.push(`--liro-heading-${level.slice(1)}-size: ${size};`)
    values.push(`--liro-heading-${level.slice(1)}-line-height: ${lineHeight};`)
  }
  values.push(
    '/* Body text: the line height and letter spacing a script uses (per-script adjustment below). */',
  )
  values.push('--liro-leading-body: var(--liro-leading-base);')
  values.push('--liro-tracking-body-text: var(--liro-tracking-body);')
  values.push('--liro-tracking-heading-text: var(--liro-tracking-heading);')

  const themed = (theme: Theme) => {
    const index = theme === 'light' ? 0 : 1
    const lines = [`color-scheme: ${theme};`, '', '/* A.2 Meanings */']
    for (const { variable, pair } of meaningEntries()) {
      lines.push(`${variable}: ${cssValue(pair[index])};`)
    }
    lines.push('', '/* A.3 Shadows */')
    for (const [size, pair] of Object.entries(SHADOWS)) {
      lines.push(`--liro-shadow-${size}: ${pair[index]};`)
    }
    return lines
  }

  const shadcn = Object.entries(SHADCN).map(([name, variable]) => `--${name}: var(${variable});`)

  const langs = (languages: readonly string[]) =>
    `:where(${languages.map((language) => `:lang(${language})`).join(', ')})`
  const base = [
    '/* The interface face, body line height and letter spacing, set where the language may',
    '   change: the root, every themed element (LiroProvider) and every element with lang. */',
    block(':where(:root, [data-liro-theme], [lang])', [
      'font-family: var(--liro-font-sans);',
      'line-height: var(--liro-leading-body);',
      'letter-spacing: var(--liro-tracking-body-text);',
    ]),
    '/* The body size inside LiroProvider; the root size stays, so rem units do not change. */',
    block(':where([data-liro-theme])', ['font-size: var(--liro-font-size-md);']),
    '/* Han characters are drawn differently in Chinese and Japanese: text marked with lang gets',
    '   its own family first. */',
    block(langs(['zh']), [`--liro-font-sans: ${sansStack(FONT_CJK_ORDER.default)};`]),
    block(langs(['zh-Hant', 'zh-TW', 'zh-HK', 'zh-MO']), [
      `--liro-font-sans: ${sansStack(FONT_CJK_ORDER['zh-Hant'])};`,
    ]),
    block(langs(['ja']), [`--liro-font-sans: ${sansStack(FONT_CJK_ORDER.ja)};`]),
    '/* Per-script adjustment: Arabic script and CJK text take the relaxed line height and no',
    '   letter spacing. */',
    block(langs(RELAXED_SCRIPT_LANGUAGES), [
      '--liro-leading-body: var(--liro-leading-relaxed);',
      '--liro-tracking-body-text: 0;',
      '--liro-tracking-heading-text: 0;',
    ]),
  ]

  return [
    HEADER,
    '/*',
    ' * Liro tokens as CSS variables (BUILD-PLAN Appendix A). Values are declared once on :root;',
    ' * meanings per theme. LiroProvider sets data-liro-theme; without it, the light theme applies.',
    ' * Any element may carry data-liro-theme, so both themes can appear on one page.',
    ' */',
    "@import './fonts.css';",
    '',
    block(':root', values),
    '',
    block('@media (prefers-reduced-motion: reduce)', [
      ':root {',
      ...Object.keys(DURATION).map((name) => `  --liro-duration-${name}: 0ms;`),
      '}',
    ]),
    '',
    block(":root,\n[data-liro-theme='light']", themed('light')),
    '',
    block("[data-liro-theme='dark']", themed('dark')),
    '',
    '/* shadcn/ui variables mapped onto Liro meanings. Declared on every themed element, so each',
    '   resolves in its own theme. */',
    block(':root,\n[data-liro-theme]', shadcn),
    '',
    '/* A.5 and P1.2 Base typography, in the lowest layer: any utility or application style wins. */',
    block('@layer base', base.join('\n').split('\n')),
    '',
  ].join('\n')
}

/** A font package and the stylesheets of it that fonts.css includes (variable weight axis only). */
export const FONT_PACKAGES: { name: string; stylesheets: string[] }[] = [
  { name: '@fontsource-variable/noto-sans', stylesheets: ['wght.css', 'wght-italic.css'] },
  { name: '@fontsource-variable/noto-sans-arabic', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/noto-sans-hebrew', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/noto-sans-sc', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/noto-sans-tc', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/noto-sans-jp', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/space-grotesk', stylesheets: ['wght.css'] },
  { name: '@fontsource-variable/inter', stylesheets: ['wght.css'] },
]

/**
 * fonts.css from the font packages' stylesheets: every @font-face keeps its unicode-range, so
 * a browser downloads a subset only when the page has a character in it. The files move from
 * ./files/ to ./fonts/. Returns the CSS and the file names it refers to.
 */
export function fontsCss(stylesheets: string[]): { css: string; files: string[] } {
  const files: string[] = []
  const faces = stylesheets
    .join('\n')
    .replace(/url\(\.\/files\/([^)]+)\)/g, (_match, file: string) => {
      files.push(file)
      return `url(./fonts/${file})`
    })
  if (/url\((?!\.\/fonts\/)/.test(faces)) {
    throw new Error('a font stylesheet refers to a file outside ./files/')
  }
  return {
    css: [
      HEADER,
      '/* Font faces of the Liro interface and brand faces (BUILD-PLAN P1.2), from Fontsource.',
      '   Licences: THIRD-PARTY-NOTICES.md (SIL Open Font License 1.1). */',
      faces.trim(),
      '',
    ].join('\n'),
    files,
  }
}

/**
 * The Tailwind v4 theme. Tailwind's own colours, radii, shadows, easings and breakpoints are
 * removed, so a raw colour such as bg-red-500 does not exist. Each meaning is exposed only to the
 * utilities it is meant for: text meanings to text-*, surfaces to bg-*, borders to border-* and
 * divide-*. So text-secondary is the secondary text colour, and bg-secondary is shadcn's.
 */
export function themeCss(): string {
  const reset = [
    '--color-*: initial;',
    '--radius-*: initial;',
    '--shadow-*: initial;',
    '--ease-*: initial;',
    '--breakpoint-*: initial;',
    '--font-*: initial;',
    '--font-weight-*: initial;',
    '--text-*: initial;',
    '--leading-*: initial;',
    '--tracking-*: initial;',
    '',
    '/* A.4 Breakpoints (literal: media queries cannot read variables) */',
    ...Object.entries(BREAKPOINTS).map(([name, value]) => `--breakpoint-${name}: ${value};`),
  ]

  const lines: string[] = ['/* A.2 Surfaces: bg-surface-page, bg-surface-raised, … */']
  for (const name of Object.keys(MEANINGS.surface)) {
    lines.push(`--background-color-surface-${kebab(name)}: var(--liro-surface-${kebab(name)});`)
  }
  lines.push('', '/* A.2 Text: text-primary, text-secondary, text-brand, text-link, … */')
  for (const name of Object.keys(MEANINGS.text)) {
    lines.push(`--text-color-${kebab(name)}: var(--liro-text-${kebab(name)});`)
  }
  lines.push(
    '',
    '/* A.2 Borders: border-default, border-strong, divide-subtle, … and focus rings */',
  )
  for (const name of Object.keys(MEANINGS.border)) {
    lines.push(`--border-color-${kebab(name)}: var(--liro-border-${kebab(name)});`)
  }
  lines.push('--outline-color-focus: var(--liro-border-focus);')
  // The control boundary also fills the parts that mark a control, such as the off track of a
  // switch (P2.1): bg-control.
  lines.push('--background-color-control: var(--liro-border-control);')
  lines.push('--ring-color-focus: var(--liro-border-focus);')
  lines.push('', '/* A.2 Brand: backgrounds, the text on them, and the accent */')
  for (const name of ['solid', 'solidHover', 'solidActive', 'subtle', 'subtleHover']) {
    lines.push(`--background-color-brand-${kebab(name)}: var(--liro-brand-${kebab(name)});`)
  }
  lines.push('--text-color-brand-on-solid: var(--liro-brand-on-solid);')
  lines.push('--color-brand-accent: var(--liro-brand-accent);')
  lines.push(
    '',
    '/* A.2 Status tones: text-status-danger-fg on bg-status-danger-bg, border-status-danger-border;',
    '   bg-/fill-/stroke-status-danger-solid for bars and dots, never for text (Appendix B.6). */',
  )
  for (const tone of Object.keys(TONES)) {
    const base = `--liro-status-${tone}`
    lines.push(`--text-color-status-${tone}-fg: var(${base}-fg);`)
    lines.push(`--background-color-status-${tone}-bg: var(${base}-bg);`)
    lines.push(`--border-color-status-${tone}-border: var(${base}-border);`)
    lines.push(`--background-color-status-${tone}-solid: var(${base}-solid);`)
    lines.push(`--fill-status-${tone}-solid: var(${base}-solid);`)
    lines.push(`--stroke-status-${tone}-solid: var(${base}-solid);`)
  }
  lines.push(
    '',
    '/* A.6 Families, for buttons: bg-family-destructive-solid (hover, active), text-on-accent on it;',
    '   bg-family-destructive-subtle (hover) with text-family-destructive-fg. */',
  )
  for (const [family, parts] of Object.entries(FAMILIES)) {
    const base = `--liro-family-${family}`
    for (const part of ['solid', 'solidHover', 'solidActive', 'subtle', 'subtleHover']) {
      if (part in parts) {
        lines.push(
          `--background-color-family-${family}-${kebab(part)}: var(${base}-${kebab(part)});`,
        )
      }
    }
    lines.push(`--text-color-family-${family}-fg: var(${base}-fg);`)
    lines.push(`--text-color-family-${family}-fg-hover: var(${base}-fg-hover);`)
  }
  lines.push('', '/* A.3 Radius (rounded-none and rounded-full are built in) and shadows */')
  for (const name of ['xs', 'sm', 'md', 'lg', 'xl']) {
    lines.push(`--radius-${name}: var(--liro-radius-${name});`)
  }
  for (const name of Object.keys(SHADOWS)) {
    lines.push(`--shadow-${name}: var(--liro-shadow-${name});`)
  }
  lines.push(
    '',
    '/* A.4 Motion: ease-standard, …; the default transition uses base and standard */',
  )
  for (const name of Object.keys(EASING)) {
    lines.push(`--ease-${name}: var(--liro-ease-${name});`)
  }
  lines.push('--default-transition-duration: var(--liro-duration-base);')
  lines.push('--default-transition-timing-function: var(--liro-ease-standard);')
  lines.push('', '/* A.4 Sizes: h-header, h-control, h-control-sm, max-w-content */')
  lines.push('--spacing-header: var(--liro-size-header-height);')
  lines.push('--spacing-control: var(--liro-size-control-height);')
  lines.push('--spacing-control-sm: var(--liro-size-control-height-sm);')
  lines.push('--container-content: var(--liro-size-content-max-width);')
  lines.push(
    '',
    '/* A.5 Typography: font-sans, font-brand, font-mono; text-xs … text-xl with the body line',
    '   height and letter spacing of the script; text-h1 … text-h6; font-regular … font-bold;',
    '   leading-tight|base|relaxed; tracking-heading|body|caps. Tabular digits: tabular-nums. */',
  )
  lines.push('--font-sans: var(--liro-font-sans);')
  lines.push('--font-brand: var(--liro-font-brand);')
  lines.push('--font-mono: var(--liro-font-mono);')
  lines.push('--default-font-family: var(--liro-font-sans);')
  lines.push('--default-mono-font-family: var(--liro-font-mono);')
  for (const name of Object.keys(FONT_SIZE)) {
    lines.push(`--text-${name}: var(--liro-font-size-${name});`)
    lines.push(`--text-${name}--line-height: var(--liro-leading-body);`)
    lines.push(`--text-${name}--letter-spacing: var(--liro-tracking-body-text);`)
  }
  for (const level of Object.keys(HEADINGS)) {
    const n = level.slice(1)
    lines.push(`--text-${level}: var(--liro-heading-${n}-size);`)
    lines.push(`--text-${level}--line-height: var(--liro-heading-${n}-line-height);`)
    lines.push(`--text-${level}--font-weight: var(--liro-font-weight-semibold);`)
    lines.push(`--text-${level}--letter-spacing: var(--liro-tracking-heading-text);`)
  }
  for (const name of Object.keys(FONT_WEIGHT)) {
    lines.push(`--font-weight-${name}: var(--liro-font-weight-${name});`)
  }
  for (const name of Object.keys(LEADING)) {
    lines.push(`--leading-${name}: var(--liro-leading-${name});`)
  }
  for (const name of Object.keys(TRACKING)) {
    lines.push(`--tracking-${name}: var(--liro-tracking-${name});`)
  }
  lines.push(
    '',
    '/* shadcn/ui names, for the copied primitives only (bg-background, text-muted-foreground, …).',
    '   text-destructive is the danger text colour, readable on surfaces. */',
  )
  for (const name of Object.keys(SHADCN)) {
    if (name !== 'radius') lines.push(`--color-${name}: var(--${name});`)
  }
  lines.push('--text-color-destructive: var(--liro-status-danger-fg);')

  return [
    HEADER,
    '/*',
    ' * Tailwind v4 theme: semantic utility names that read the --liro-* variables of tokens.css.',
    ' * `inline` makes utilities reference the variables directly, so each theme resolves on its own',
    ' * element. Import after tailwindcss: @import "tailwindcss"; @import "@veljaos/tokens/theme.css";',
    ' */',
    block('@theme', reset),
    '',
    block('@theme inline', lines),
    '',
  ].join('\n')
}

export function tokensJson(): string {
  return `${JSON.stringify(resolvedTokens(), null, 2)}\n`
}
