/**
 * Writes the three published files of @veljaos/tokens from src/tokens.ts:
 * tokens.css (the --liro-* variables), theme.css (the Tailwind v4 theme) and tokens.json.
 */
import {
  BREAKPOINTS,
  COMMON,
  DURATION,
  EASING,
  kebab,
  LAYERS,
  MEANINGS,
  meaningEntries,
  RADIUS,
  RAMPS,
  resolvedTokens,
  SHADOWS,
  SIZES,
  SPACE,
  TONES,
  valueVariable,
  type Theme,
} from './tokens.ts'

const HEADER = '/* Generated by @veljaos/tokens from src/tokens.ts. Do not edit. */'

/** A meaning's value in CSS: a value reference becomes var(--liro-…), a literal stays. */
function cssValue(reference: string): string {
  const variable = valueVariable(reference)
  return variable === null ? reference : `var(${variable})`
}

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((line) => (line === '' ? '' : `  ${line}`)).join('\n')}\n}`
}

/**
 * shadcn/ui's variables mapped onto Liro meanings, so copied primitives look Liro without edits.
 * Liro components use the Liro names.
 */
export const SHADCN: Record<string, string> = {
  radius: '--liro-radius-md',
  background: '--liro-surface-page',
  foreground: '--liro-text-primary',
  card: '--liro-surface-raised',
  'card-foreground': '--liro-text-primary',
  popover: '--liro-surface-overlay',
  'popover-foreground': '--liro-text-primary',
  primary: '--liro-brand-solid',
  'primary-foreground': '--liro-brand-on-solid',
  secondary: '--liro-surface-sunken',
  'secondary-foreground': '--liro-text-primary',
  muted: '--liro-surface-sunken',
  'muted-foreground': '--liro-text-secondary',
  accent: '--liro-surface-hover',
  'accent-foreground': '--liro-text-primary',
  destructive: '--liro-status-danger-solid',
  'destructive-foreground': '--liro-text-on-accent',
  border: '--liro-border-default',
  input: '--liro-border-strong',
  ring: '--liro-border-focus',
}

export function tokensCss(): string {
  const values: string[] = ['/* A.1 Colour ramps (0 = lightest, 9 = darkest) and common colours */']
  for (const [ramp, steps] of Object.entries(RAMPS)) {
    steps.forEach((value, step) => values.push(`--liro-${ramp}-${String(step)}: ${value};`))
  }
  for (const [name, value] of Object.entries(COMMON)) {
    values.push(`--liro-${kebab(name)}: ${value};`)
  }
  values.push('', '/* A.3 Spacing and radius */')
  for (const [name, value] of Object.entries(SPACE)) values.push(`--liro-space-${name}: ${value};`)
  for (const [name, value] of Object.entries(RADIUS))
    values.push(`--liro-radius-${name}: ${value};`)
  values.push(
    '',
    '/* A.4 Motion, breakpoints (for reference: media queries cannot read variables), sizes, layers */',
  )
  for (const [name, value] of Object.entries(DURATION))
    values.push(`--liro-duration-${name}: ${value};`)
  for (const [name, value] of Object.entries(EASING)) values.push(`--liro-ease-${name}: ${value};`)
  for (const [name, value] of Object.entries(BREAKPOINTS))
    values.push(`--liro-breakpoint-${name}: ${value};`)
  for (const [name, value] of Object.entries(SIZES))
    values.push(`--liro-size-${kebab(name)}: ${value};`)
  for (const [name, value] of Object.entries(LAYERS)) values.push(`--liro-layer-${name}: ${value};`)

  const themed = (theme: Theme) => {
    const index = theme === 'light' ? 0 : 1
    const lines = [`color-scheme: ${theme};`, '', '/* A.2 Meanings */']
    for (const { variable, pair } of meaningEntries()) {
      lines.push(`${variable}: ${cssValue(pair[index])};`)
    }
    lines.push('', '/* A.3 Shadows */')
    for (const [size, pair] of Object.entries(SHADOWS)) {
      lines.push(`--liro-shadow-${size}: ${pair[index]};`)
    }
    return lines
  }

  const shadcn = Object.entries(SHADCN).map(([name, variable]) => `--${name}: var(${variable});`)

  return [
    HEADER,
    '/*',
    ' * Liro tokens as CSS variables (BUILD-PLAN Appendix A). Values are declared once on :root;',
    ' * meanings per theme. LiroProvider sets data-liro-theme; without it, the light theme applies.',
    ' * Any element may carry data-liro-theme, so both themes can appear on one page.',
    ' */',
    block(':root', values),
    '',
    block('@media (prefers-reduced-motion: reduce)', [
      ':root {',
      ...Object.keys(DURATION).map((name) => `  --liro-duration-${name}: 0ms;`),
      '}',
    ]),
    '',
    block(":root,\n[data-liro-theme='light']", themed('light')),
    '',
    block("[data-liro-theme='dark']", themed('dark')),
    '',
    '/* shadcn/ui variables mapped onto Liro meanings. Declared on every themed element, so each',
    '   resolves in its own theme. */',
    block(':root,\n[data-liro-theme]', shadcn),
    '',
  ].join('\n')
}

/**
 * The Tailwind v4 theme. Tailwind's own colours, radii, shadows, easings and breakpoints are
 * removed, so a raw colour such as bg-red-500 does not exist. Each meaning is exposed only to the
 * utilities it is meant for: text meanings to text-*, surfaces to bg-*, borders to border-* and
 * divide-*. So text-secondary is the secondary text colour, and bg-secondary is shadcn's.
 */
export function themeCss(): string {
  const reset = [
    '--color-*: initial;',
    '--radius-*: initial;',
    '--shadow-*: initial;',
    '--ease-*: initial;',
    '--breakpoint-*: initial;',
    '',
    '/* A.4 Breakpoints (literal: media queries cannot read variables) */',
    ...Object.entries(BREAKPOINTS).map(([name, value]) => `--breakpoint-${name}: ${value};`),
  ]

  const lines: string[] = ['/* A.2 Surfaces: bg-surface-page, bg-surface-raised, … */']
  for (const name of Object.keys(MEANINGS.surface)) {
    lines.push(`--background-color-surface-${kebab(name)}: var(--liro-surface-${kebab(name)});`)
  }
  lines.push('', '/* A.2 Text: text-primary, text-secondary, text-brand, text-link, … */')
  for (const name of Object.keys(MEANINGS.text)) {
    lines.push(`--text-color-${kebab(name)}: var(--liro-text-${kebab(name)});`)
  }
  lines.push(
    '',
    '/* A.2 Borders: border-default, border-strong, divide-subtle, … and focus rings */',
  )
  for (const name of Object.keys(MEANINGS.border)) {
    lines.push(`--border-color-${kebab(name)}: var(--liro-border-${kebab(name)});`)
  }
  lines.push('--outline-color-focus: var(--liro-border-focus);')
  lines.push('--ring-color-focus: var(--liro-border-focus);')
  lines.push('', '/* A.2 Brand: backgrounds, the text on them, and the accent */')
  for (const name of ['solid', 'solidHover', 'solidActive', 'subtle', 'subtleHover']) {
    lines.push(`--background-color-brand-${kebab(name)}: var(--liro-brand-${kebab(name)});`)
  }
  lines.push('--text-color-brand-on-solid: var(--liro-brand-on-solid);')
  lines.push('--color-brand-accent: var(--liro-brand-accent);')
  lines.push(
    '',
    '/* A.2 Status tones: text-status-danger-fg on bg-status-danger-bg, border-status-danger-border;',
    '   bg-/fill-/stroke-status-danger-solid for bars and dots, never for text (Appendix B.6). */',
  )
  for (const tone of Object.keys(TONES)) {
    const base = `--liro-status-${tone}`
    lines.push(`--text-color-status-${tone}-fg: var(${base}-fg);`)
    lines.push(`--background-color-status-${tone}-bg: var(${base}-bg);`)
    lines.push(`--border-color-status-${tone}-border: var(${base}-border);`)
    lines.push(`--background-color-status-${tone}-solid: var(${base}-solid);`)
    lines.push(`--fill-status-${tone}-solid: var(${base}-solid);`)
    lines.push(`--stroke-status-${tone}-solid: var(${base}-solid);`)
  }
  lines.push('', '/* A.3 Radius (rounded-none and rounded-full are built in) and shadows */')
  for (const name of ['xs', 'sm', 'md', 'lg', 'xl']) {
    lines.push(`--radius-${name}: var(--liro-radius-${name});`)
  }
  for (const name of Object.keys(SHADOWS)) {
    lines.push(`--shadow-${name}: var(--liro-shadow-${name});`)
  }
  lines.push(
    '',
    '/* A.4 Motion: ease-standard, …; the default transition uses base and standard */',
  )
  for (const name of Object.keys(EASING)) {
    lines.push(`--ease-${name}: var(--liro-ease-${name});`)
  }
  lines.push('--default-transition-duration: var(--liro-duration-base);')
  lines.push('--default-transition-timing-function: var(--liro-ease-standard);')
  lines.push('', '/* A.4 Sizes: h-header, h-control, h-control-sm, max-w-content */')
  lines.push('--spacing-header: var(--liro-size-header-height);')
  lines.push('--spacing-control: var(--liro-size-control-height);')
  lines.push('--spacing-control-sm: var(--liro-size-control-height-sm);')
  lines.push('--container-content: var(--liro-size-content-max-width);')
  lines.push(
    '',
    '/* shadcn/ui names, for the copied primitives only (bg-background, text-muted-foreground, …).',
    '   text-destructive is the danger text colour, readable on surfaces. */',
  )
  for (const name of Object.keys(SHADCN)) {
    if (name !== 'radius') lines.push(`--color-${name}: var(--${name});`)
  }
  lines.push('--text-color-destructive: var(--liro-status-danger-fg);')

  return [
    HEADER,
    '/*',
    ' * Tailwind v4 theme: semantic utility names that read the --liro-* variables of tokens.css.',
    ' * `inline` makes utilities reference the variables directly, so each theme resolves on its own',
    ' * element. Import after tailwindcss: @import "tailwindcss"; @import "@veljaos/tokens/theme.css";',
    ' */',
    block('@theme', reset),
    '',
    block('@theme inline', lines),
    '',
  ].join('\n')
}

export function tokensJson(): string {
  return `${JSON.stringify(resolvedTokens(), null, 2)}\n`
}
